Adds new operations to pmc workload
opensearch-project/opensearch-benchmark-workloads pull request #137
Opened 2023-10-31 17:52 UTC by harshavamsi

Adds new Operations to the PMC workload to support nested prefix queries

Signed-off-by: Harsha Vamsi Kalluri <hvamsi@amazon.com>

2023-10-31 18:26 UTC, IanHoang reviewed
@harshavamsi As standard procedure, could you run the PMC workload with these latest changes in `--test-mode` and provide the sample of the output in the PR description? This will ensure that there are no issues before merging this in.

2023-10-31 18:42 UTC, harshavamsi commented
@IanHoang here's a sample run from the new test procedure.

```
opensearch-benchmark-workloads git:(main) opensearch-benchmark execute-test --pipeline=benchmark-only --workload=pmc --target-host="opense-clust-JeMftrsCHhzL-4e64d68df0dff2e6.elb.us-west-2.amazonaws.com:80"  --workload-repository="/home/hvamsi/code/opensearch-benchmark-workloads" --kill-running-processes --test-procedure="append-and-prefix" --test-mode

   ____                  _____                      __       ____                  __                         __
  / __ \____  ___  ____ / ___/___  ____ ___________/ /_     / __ )___  ____  _____/ /_  ____ ___  ____ ______/ /__
 / / / / __ \/ _ \/ __ \\__ \/ _ \/ __ `/ ___/ ___/ __ \   / __  / _ \/ __ \/ ___/ __ \/ __ `__ \/ __ `/ ___/ //_/
/ /_/ / /_/ /  __/ / / /__/ /  __/ /_/ / /  / /__/ / / /  / /_/ /  __/ / / / /__/ / / / / / / / / /_/ / /  / ,<
\____/ .___/\___/_/ /_/____/\___/\__,_/_/   \___/_/ /_/  /_____/\___/_/ /_/\___/_/ /_/_/ /_/ /_/\__,_/_/  /_/|_|
    /_/

[INFO] Executing test with workload [pmc], test_procedure [append-and-prefix] and provision_config_instance ['external'] with version [3.0.0-SNAPSHOT].

[WARNING] merges_total_time is 4280354 ms indicating that the cluster is not in a defined clean state. Recorded index time metrics may be misleading.
[WARNING] merges_total_throttled_time is 167378 ms indicating that the cluster is not in a defined clean state. Recorded index time metrics may be misleading.
[WARNING] indexing_total_time is 13910583 ms indicating that the cluster is not in a defined clean state. Recorded index time metrics may be misleading.
[WARNING] refresh_total_time is 407720 ms indicating that the cluster is not in a defined clean state. Recorded index time metrics may be misleading.
[WARNING] flush_total_time is 432345 ms indicating that the cluster is not in a defined clean state. Recorded index time metrics may be misleading.
Running put-settings                                                           [100% done]
Running delete-index                                                           [100% done]
Running create-index                                                           [100% done]
Running check-cluster-health                                                   [100% done]
Running index-append                                                           [100% done]
Running refresh-after-index                                                    [100% done]
Running force-merge                                                            [100% done]
Running refresh-after-force-merge                                              [100% done]
Running wait-until-merges-finish                                               [100% done]
Running prefix_index                                                           [100% done]
Running prefix_docvalues                                                       [100% done]
Running prefix_indexordocvalues                                                [100% done]
Running nested_prefix_index                                                    [100% done]
Running nested_prefix_docvalues                                                [100% done]
Running nested_prefix_indexordocvalues                                         [100% done]

------------------------------------------------------
    _______             __   _____
   / ____(_)___  ____ _/ /  / ___/_________  ________
  / /_  / / __ \/ __ `/ /   \__ \/ ___/ __ \/ ___/ _ \
 / __/ / / / / / /_/ / /   ___/ / /__/ /_/ / /  /  __/
/_/   /_/_/ /_/\__,_/_/   /____/\___/\____/_/   \___/
------------------------------------------------------
            
|                                                         Metric |                           Task |       Value |   Unit |
|---------------------------------------------------------------:|-------------------------------:|------------:|-------:|
|                     Cumulative indexing time of primary shards |                                |     231.846 |    min |
|             Min cumulative indexing time across primary shards |                                |     0.01165 |    min |
|          Median cumulative indexing time across primary shards |                                |     0.01255 |    min |
|             Max cumulative indexing time across primary shards |                                |     231.784 |    min |
|            Cumulative indexing throttle time of primary shards |                                |           0 |    min |
|    Min cumulative indexing throttle time across primary shards |                                |           0 |    min |
| Median cumulative indexing throttle time across primary shards |                                |           0 |    min |
|    Max cumulative indexing throttle time across primary shards |                                |           0 |    min |
|                        Cumulative merge time of primary shards |                                |     71.3392 |    min |
|                       Cumulative merge count of primary shards |                                |         105 |        |
|                Min cumulative merge time across primary shards |                                |           0 |    min |
|             Median cumulative merge time across primary shards |                                |           0 |    min |
|                Max cumulative merge time across primary shards |                                |     71.3392 |    min |
|               Cumulative merge throttle time of primary shards |                                |     2.78963 |    min |
|       Min cumulative merge throttle time across primary shards |                                |           0 |    min |
|    Median cumulative merge throttle time across primary shards |                                |           0 |    min |
|       Max cumulative merge throttle time across primary shards |                                |     2.78963 |    min |
|                      Cumulative refresh time of primary shards |                                |     6.79487 |    min |
|                     Cumulative refresh count of primary shards |                                |         153 |        |
|              Min cumulative refresh time across primary shards |                                |       0.003 |    min |
|           Median cumulative refresh time across primary shards |                                |  0.00325833 |    min |
|              Max cumulative refresh time across primary shards |                                |     6.77888 |    min |
|                        Cumulative flush time of primary shards |                                |     7.20575 |    min |
|                       Cumulative flush count of primary shards |                                |          32 |        |
|                Min cumulative flush time across primary shards |                                |           0 |    min |
|             Median cumulative flush time across primary shards |                                |           0 |    min |
|                Max cumulative flush time across primary shards |                                |     7.20575 |    min |
|                                        Total Young Gen GC time |                                |       0.008 |      s |
|                                       Total Young Gen GC count |                                |           1 |        |
|                                          Total Old Gen GC time |                                |           0 |      s |
|                                         Total Old Gen GC count |                                |           0 |        |
|                                                     Store size |                                |     24.2149 |     GB |
|                                                  Translog size |                                | 3.07336e-07 |     GB |
|                                         H [...]

2023-11-03 21:56 UTC, harshavamsi commented
Hi @IanHoang can we merge this so that it can be picked up by the nightly benchmarking?

2023-11-07 03:55 UTC, gkamat requested changes

2023-11-07 03:55 UTC, gkamat commented on pmc/index.json
> +        "copy_to": ["name_docvalues", "name_indexordocvalues"]
What is the reason the default for `doc_values` being changed for the `name` field?  Any additions to the workload should not modify the existing mapping.

2024-02-02 23:09 UTC, closed without merging

2024-02-02 23:10 UTC, IanHoang commented
Spoke to @harshavamsi and am closing this out